---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by galax.
--- DateTime: 6/6/2020 6:16 PM
---

function SieveOfEratosthenes(n)
    prime = {}
    for i = 0, n - 1 do
        prime[i] = true
    end

    p = 2
    while p * p <= n do
        if prime[p] then
            for i = p * p, n, p do
                prime[i] = false
            end
        end
        p = p + 1
    end

    result = {}
    count = 1
    for i = 2, n do
        if prime[i] then
            result[count] = i
            count = count + 1
        end
    end
    return result
end

simplediv = {}
function simplediv.solve(a, b)
    primes = SieveOfEratosthenes(b)
    for k, v in pairs(primes) do
        if b % a ~= 0 then
            return false
        end

    end
    return true
end

print(simplediv.solve(54,2834359))

return simplediv


