---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by galax.
--- DateTime: 6/6/2020 9:00 PM
---

BankAccount = {
    account_number = 0,
    holder_name = "",
    balance = 0.0
}

function BankAccount:deposit(amount)
    self.balance = self.balance + amount
end

function BankAccount:withdraw(amount)
    self.balance = self.balance - amount
end

function BankAccount:new(t)
    -- Make sure t is not nil
    t = t or {}
    setmetatable(t ,self)
    self.__index = self
    return t
end

----------------------------------------------------------------
-- Create an object
----------------------------------------------------------------

johns_account = BankAccount:new({
    account_number = 12345,
    holder_name = "John Coltrane",
    balance = 0.0
})

johns_account:deposit(5000)

print("Johns balance: "..johns_account.balance)