---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by galax.
--- DateTime: 6/7/2020 12:22 AM
---

function f()
    print("f, A")
    coroutine.yield()
    print("f, B")
end

c = coroutine.create(f)
print(type(c))

print(coroutine.status(c))

coroutine.resume(c)
coroutine.resume(c)
print(coroutine.status(c))