---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by galax.
--- DateTime: 6/6/2020 10:47 PM
---

students = {
    { name = "Miles Davis", instrument = "trumpet" },
    { name = "John Coltrane", instrument = "saxophone" },
    { name = "Bill Evans", instrument = "piano" },
    { name = "Wynton Kelly", instrument = "piano" },

}

    s = table.sort(students, function(a, b)
        return a.name > b.name
    end)


function funcA(a)
    local c = 10
    function funcB(b)
        return a + b + c
    end
    return funcB
end

algo = funcA(10)
print(algo(20))
