---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by galax.
--- DateTime: 6/5/2020 8:01 PM
---

--quiz_scores = {["Player1"] = 90, ["Player2"] = 90}
--quiz_scores["Player3"] = 95

--print(quiz_scores["Player1"])

-- pairs

quiz_scores = {
    Player1 = 1,
    Player2 = 2,
    Player3 = 3
}
print(quiz_scores["Player1"])

for k, v in pairs(quiz_scores) do
    print("Key: " .. k .. " Value: " .. v)

end


-- ipairs
alphabet = { "A", "B", "C", "D", "E", "F" }

for i, v in ipairs(alphabet) do
    print("Index: " .. i .. " Value: " .. v)

end

local playerPos = { x = 400, y = 300 }
local enemyPos = { x = 0, y = 0 }

print("Player is at position: (" .. playerPos.x .. ", " .. playerPos.y .. ")")
print("Enemy is at position: (" .. enemyPos["x"] .. ", " .. enemyPos["y"] .. ")")

-- multiple row table
codeKeys = {
    { Page = 10, line = 6, Word = 2, Code = "A" },
    { Page = 1, line = 6, Word = 2, Code = "B" },
    { Page = 2, line = 6, Word = 2, Code = "C" },
    { Page = 3, line = 6, Word = 2, Code = "D" },
    { Page = 4, line = 6, Word = 2, Code = "E" },
    { Page = 15, line = 6, Word = 2, Code = "F" },
}
print("Enter the page number: ")
local page = io.read("*n")
print("Enter the line index: ")
local line = io.read("*n")
print("Enter the word index: ")
local word = io.read("*n")

--[[ How to search the code of page, line, word --]]
for _, v in pairs(codeKeys) do
    if v.Page == page and v.line == line and v.Word == word then
        print("The code is "..v.Code)
    end
end

-- Use table as matrix
mat = {}

N = 3
M = 4
for i = 1, N do
    mat[i] = {}
    for j = 1, M do
        mat[i][j] = 0
    end
end