---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by galax.
--- DateTime: 6/5/2020 10:06 PM
---

local board = {}

function clear_board()
    for i = 1, 3 do
        board[i] = {}
        for j = 1, 3  do
            board[i][j] = " "
        end
    end
end

function display_board()
    print("  1 2 3 ")
    for i = 1, 3 do
        print(i.." ["..board[i][1].." ][ "..board[i][2].."]["..board[i][3].."]")
    end
end

function board_full()
    for i = 1, 3 do
        for j = 1, 3 do
            if board[i][j] == " " then
                return false
            end
        end
    end
    return true

end

function check_winner()
    -- check rows
    if board[1][1] ~= " " and board[1][1] == board[1][2] and board[1][1] == board[1][3] then return board[1][1] end
    if board[2][1] ~= " " and board[2][1] == board[2][2] and board[2][1] == board[2][3] then return board[2][1] end
    if board[3][1] ~= " " and board[3][1] == board[3][2] and board[3][1] == board[3][3] then return board[3][1] end

    -- check cols
    if board[1][1] ~= " " and board[1][1] == board[2][1] and board[2][1] == board[3][1] then return board[1][1] end
    if board[1][2] ~= " " and board[1][2] == board[2][2] and board[2][2] == board[3][2] then return board[1][2] end
    if board[1][3] ~= " " and board[1][3] == board[2][3] and board[2][3] == board[3][3] then return board[1][3] end

    -- check diagonals
    if board[1][1] ~= " " and board[1][1] == board[2][2] and board[2][2] == board[3][3] then return board[1][1] end
    if board[1][3] ~= " " and board[1][3] == board[2][2] and board[2][2] == board[3][1] then return board[1][3] end

    -- if there is no winner
    return nil
    
end

local player = "X"
local move = 1
local game_over = false

clear_board()

while not game_over do
    displayMenu()

    print("Enter the row you want to place the symbol "..player..": ")
    local row_to_play = io.read("*n")

    print("Enter the col you want to place the symbol "..player..": ")
    local col_to_play = io.read("*n")

    if move % 2 == 0 then
        player = "X"
    else
        player = "O"
    end

    move = move + 1

    local winner = check_winner()
    if winner ~= nil then
        display_board()
        print("Winner is "..winner)
        game_over = true
    elseif board_full() then
        print("Tie")
        game_over = true
    end
end

