---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by galax.
--- DateTime: 6/7/2020 3:21 PM
---

-- 2D array
local N = 3
local M = 3
mt = {}
for i = 1, N do
    mt[i] = {}
    for j = 1, M do
        mt[i][j] = i*j
    end
end

mt{}
for i = 1, N do
    for j = 1, M do
        mt[j+(i-1)*M] = i*j
    end

end

-- 2D array (Alternative)
